### ISSUE TITLE
css: center horizontally

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/notes#399]
```css
button {
    margin:0 auto;
    display:block;
  }
  a {
    display:block;
    text-align:center;
  }
```
