### ISSUE TITLE
CircleCI react native cocoapods

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/notes#402]
```
steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: cd ios && bundle exec pod install
      - run: xcodebuild -workspace ios/MyApp.xcworkspace -scheme "MyApp Staging" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone X' -UseModernBuildSystem=NO
```
